version: '2'
services:
    payara-full:
        build: mypayara-full
        ports:
            - "8080:8080"
            - "4848:4848"
        entrypoint:
            - /opt/payara41/bin/asadmin
            - start-domain
            - -v
        depends_on:
            - db

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: glassfishdbpassword
            POSTGRES_USER: glassfish
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./data/pgdata:/var/lib/postgresql/data/pgdata
